# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [ ]:
import numpy as np
import csv 
arr = np.loadtxt('minutes_n_ingredients.csv', delimiter = ',', dtype = np.int32, skiprows = 1)
arr[:5]

OSError: ignored

In [ ]:
np.random.randint(0, 20, size = (4, 7))

array([[ 4, 10, 12, 18,  3,  0, 12],
       [ 0,  8,  6,  4,  2,  1, 11],
       [ 8, 17,  1, 10, 17,  6,  8],
       [ 7,  1,  9, 11,  6, 16, 11]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [ ]:
np.random.randint(0, 10, size = (8, 10))

array([[3, 7, 9, 1, 9, 6, 9, 3, 2, 9],
       [7, 8, 9, 7, 8, 3, 1, 5, 3, 9],
       [1, 4, 2, 3, 9, 4, 1, 5, 4, 1],
       [1, 4, 7, 9, 4, 7, 6, 8, 7, 8],
       [0, 9, 4, 7, 8, 4, 5, 2, 4, 6],
       [6, 1, 2, 9, 6, 8, 1, 9, 0, 2],
       [5, 2, 4, 5, 9, 2, 1, 7, 5, 1],
       [9, 2, 8, 5, 1, 4, 7, 9, 6, 2]])

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [ ]:
import matplotlib.pyplot as pl
from mpl_toolkits.mplot3d import Axes3D

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [ ]:
import numpy as np
import csv 
arr1 = np.loadtxt('/boot/csv файл/minutes_n_ingredients.csv', delimiter = ',', dtype = np.int32, skiprows = 1)
arr1[:5]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]], dtype=int32)

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [ ]:
import numpy as np
data = np.loadtxt('/boot/csv файл/minutes_n_ingredients.csv', delimiter = ',', dtype = np.int32, skiprows = 1)
data[:,1:]
means = np.mean(data, axis = 0)
mins = np.min(data, axis =0)
maxs = np.max(data, axis = 0)
medians = np.median(data, axis = 0)
print('Means: ', means)
print('Mins: ', mins)
print('Maxs: ', maxs)
print('Medians: ', medians)

Means:  [2.22064324e+05 2.16010017e+04 9.05528000e+00]
Mins:  [38  0  1]
Maxs:  [    537671 2147483647         39]
Medians:  [2.071935e+05 4.000000e+01 9.000000e+00]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [ ]:
import numpy as np
data = np.loadtxt('/boot/csv файл/minutes_n_ingredients.csv', delimiter = ',', dtype = np.int32, skiprows = 1)
q = np.quantile(data[:,1:2], q=0.75, axis =0)
print(data[data[:,1]<=q])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [ 43407     35      7]
 [498432     65     15]
 [370915      5      4]]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [ ]:
import numpy as np
data = np.loadtxt('/boot/csv файл/minutes_n_ingredients.csv', delimiter = ',', dtype = np.int32, skiprows = 1)
print(len(data[data[:,1]==0]))
data[data[:,1]==0] = 1

479


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [ ]:
import numpy as np
data = np.loadtxt('/boot/csv файл/minutes_n_ingredients.csv', delimiter = ',', dtype = np.int32, skiprows = 1)
len(np.unique(data[:,0]))

100000

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [ ]:
import numpy as np
data = np.loadtxt('/boot/csv файл/minutes_n_ingredients.csv', delimiter = ',', dtype = np.int32, skiprows = 1)
num = set(data[:,2])
print(len(num))

37


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [ ]:
import numpy as np
data = np.loadtxt('/boot/csv файл/minutes_n_ingredients.csv', delimiter = ',', dtype = np.int32, skiprows = 1)
arr5 = data[data[:,2] <= 5]
arr5

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]], dtype=int32)

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [ ]:
import numpy as np
data = np.loadtxt('/boot/csv файл/minutes_n_ingredients.csv', delimiter = ',', dtype = np.int32, skiprows = 1)
value = data[:,2] / data[:,1]
print(value.max(axis = 0))

inf


<ipython-input-23-2c3f75dd6b89>:3: RuntimeWarning: divide by zero encountered in true_divide
  value = data[:,2] / data[:,1]


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [ ]:
import numpy as np
data = np.loadtxt('/boot/csv файл/minutes_n_ingredients.csv', delimiter = ',', dtype = np.int32, skiprows = 1)
sorted = data[data[:,1].argsort()]
sorted = sorted[-100:]
np.mean(sorted[:,2])

6.61

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [ ]:
import numpy as np
data = np.loadtxt('/boot/csv файл/minutes_n_ingredients.csv', delimiter = ',', dtype = np.int32, skiprows = 1)
n = 10
index = np.random.choice(data.shape[0], n, replace = False)
data[index]

array([[436611,     85,     10],
       [ 35441,     55,      9],
       [362179,     30,     11],
       [335476,     25,      4],
       [400643,     30,      9],
       [217420,     15,      7],
       [198776,    270,     12],
       [   290,     66,     12],
       [510756,     45,      7],
       [163200,     35,      8]], dtype=int32)

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [ ]:
import numpy as np
data = np.loadtxt('/boot/csv файл/minutes_n_ingredients.csv', delimiter = ',', dtype = np.int32, skiprows = 1)
means = np.mean(data[:,2])
lessmean = len(data[data[:,2] < means])
per = 100*lessmean / len(data)
per

58.802

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [ ]:
import numpy as np
data = np.loadtxt('/boot/csv файл/minutes_n_ingredients.csv', delimiter = ',', dtype = np.int32, skiprows = 1)
data2 = data.copy()
prost = [1 if (row[1] <= 20) & (row[2] <=5) else 0 for row in data2]
new_data = np.insert(data2, 3, prost, axis = 1)
print(new_data)

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993    140     14      0]]


13. Выведите процент "простых" рецептов в датасете

In [ ]:
import numpy as np
data = np.loadtxt('/boot/csv файл/minutes_n_ingredients.csv', delimiter = ',', dtype = np.int32, skiprows = 1)
data2 = data.copy()
prost = [1 if (row[1] <= 20) & (row[2] <=5) else 0 for row in data2]
new_data = np.insert(data2, 3, prost, axis = 1)
percent = (new_data[:,3] == 1)
len(data[percent, :])/len(new_data)*100

9.552

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.